version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:battleshipPostgres@db:5432/battleship
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: battleship_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: battleshipPostgres
      POSTGRES_DB: battleship
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
